Make carbonifer available as Go library
carboniferio/carbonifer pull request #41
Opened 2023-02-23 21:40 UTC by Joffref

Closes: #40

Thanks to this PR `GetEstimationFromInstanceType()`, `GetEstimation()` and  `GetResource()` will be available as part of carbonifer Go Lib.

Note to the maintainers: I had struggle with the way viper is used to import data, I make an ugly workaround. I'm open to your suggestion on this point in order to find the best way to patch this. :smile:

2023-02-24 18:01 UTC, obierlaire commented
Thanks a lot @Joffref for this first contribution ❤️ That's much appreciated !
I haven't had time to properly review it yet, that's a nice work!
However, I've noticed a few things: 
- CI is failing: [golangci-cli  found one tiny error ](https://github.com/carboniferio/carbonifer/actions/runs/4257086100/jobs/7422172534)
- Even if it's pretty straightforward `GetEstimation()` should have a test. It's not a big deal if you don't have time though.

The viper part does not look that ugly, I'll have a look later to see if we can find a nicer way

Again, thanks!

2023-02-24 22:54 UTC, Joffref commented
Hey @obierlaire, I've made few changes on the PR, based on your comments. Hope it will be good this time, let me know if there is something to modify in it.

2023-02-27 17:30 UTC, obierlaire requested changes
I think you need to rebase once https://github.com/carboniferio/carbonifer/pull/47 will be merged

2023-02-27 21:03 UTC, Joffref commented
> I think you need to rebase once #47 will be merged

I agree :+1: Waiting to the update on your side

2023-02-28 09:43 UTC, obierlaire commented
#47 merged, you can rebase your branch

2023-02-28 21:23 UTC, Joffref commented on pkg/estimate/estimate_test.go
> +				Power:           decimal.NewFromFloat(4.8677297799),
Yes, after a retry with default config it appears that those values are wrong.

2023-02-28 21:23 UTC, Joffref commented on pkg/estimate/estimate.go
> +			CPUType:           resource.CPUTypes[0], // TODO: Support multiple CPU types
Make sense

2023-03-02 17:42 UTC, obierlaire commented
@Joffref I pushed [ad7d82f](https://github.com/carboniferio/carbonifer/pull/41/commits/ad7d82f16f162d2b19aaf27fba748a5099f8b19e) to your PR in order to have one single rationalized way to init Viper and set `data.path` variable, always from the go project root directory, and not relative to the caller. That's more DRY and seems to work...

2023-03-02 17:42 UTC, obierlaire approved these changes

2023-03-02 21:56 UTC, Joffref commented
Nice one ! It will be better like this :+1:

2023-03-03 07:56 UTC, merged